### ISSUE TITLE
[FEATURE] - Projects

### ISSUE THREAD

**Issue by gonzalezkrause** [Gocaio/goca#11]
Goca must be able to handle "projects". As a first approach it would be nice if all the output can be stored on a per project database with the downloaded files, scan options and the recovered metadata for each file.

The main database operations could be:

- [x] Store all the data inside the project database.
- [x] Load an already existing project.
~- [ ] Re-scan all the files of an existing project updating its database (Useful for the case that new plugins had been added).~ (for v0.3.0)

As a final tip, a BBolt (CoreOS) can be a nice database for this purpose.

**Comment by DamiaPoquet** [comment]
The re-scan option will be implemented on v0.3.0

**Comment by gonzalezkrause** [comment]
Updated the issue to reflect the reschedule of the re-scan functionality.
