### ISSUE TITLE
[FEATURE] - Add random User-Agent

### ISSUE THREAD

**Issue by Xumeiquer** [Gocaio/goca#16]
Goca has an option to set a custom User-Agent, it would be a nice feature to add a random User-Agent option so Goca will use a different User-Agent in each run.

**Comment by joanbono** [comment]
**sqlmap** does this with `--random-agent` option. 
It takes the User-Agents from this [huge list](https://github.com/sqlmapproject/sqlmap/blob/master/txt/user-agents.txt).

Maybe we can use them also, or few of them.

**Comment by DamiaPoquet** [comment]
I'll work on it

**Comment by Xumeiquer** [comment]
Finally implemeted with this [list](https://gist.githubusercontent.com/pzb/b4b6f57144aea7827ae4/raw/cf847b76a142955b1410c8bcef3aabe221a63db1/user-agents.txt)
