### ISSUE TITLE
[BUG] - Goca not working on Windows 7

### ISSUE THREAD

**Issue by beren744** [Gocaio/goca#8]
**Describe the bug**

GOCA_windows_amd64.zip   on windows seven is not working

**To Reproduce**
1. Command executed
2. Query searched

**Expected behavior**

**Screenshots**

**Environment**
1. OS
2. Go version

**Comment by joanbono** [comment]
Can you provide more information?
Is your Windows 7 32 or 64 bits?

Can you paste the output of your **cmd** executing Goca?

Thanks @beren744

**Comment by joanbono** [comment]
Hi @beren744 ,

It works for me on Windows 7 64 bits.

![image](https://user-images.githubusercontent.com/7288621/54083793-d272c300-4328-11e9-9c87-e8a3aa0db7b7.png)

Please provide detailed information about which is your issue.

Thanks

**Comment by beren744** [comment]
![immagine](https://user-images.githubusercontent.com/7878075/54090496-14295b00-4375-11e9-9196-89869fcb0d1c.png)

**Comment by beren744** [comment]
I assumed wrongly that there should have been a GUI.  It is just a command line tool instead. Right?

**Comment by beren744** [comment]
![immagine](https://user-images.githubusercontent.com/7878075/54090808-82235180-4378-11e9-8d43-bc0cdec91355.png)

**Comment by joanbono** [comment]
Hi @beren744

Right now it is only working through command line.

We are working on a GUI also, but fot future releases
