### ISSUE TITLE
[FEATURE] - New metadata modules

### ISSUE THREAD

**Issue by joanbono** [Gocaio/goca#9]
## ⚠️ Call to Open Source comunity!

This is a call to the community to get help implementing modules for multiple file formats.

As we describe here:

+ [**Creating a Plugin for Goca**](https://github.com/gocaio/Doc/blob/master/doc/0x02-PluginSystem.md)

It's a step by step guide on how to create new plugins.

Missing plugins:

+ [x] Adobe Encapsulated PostScript (.eps)
+ [x] Adobe Flash (.swf)
+ [x] Adobe Illustrator (.ai)
+ [x] Adobe Photoshop (.psd)
+ [x] Adobe Portable Document Format (.pdf)
+ [x] Adobe PostScript (.ps)
+ [ ] Autodesk Design Web Format (.dwf)
+ [x] DS_Store (.DS_Store)
+ [ ] Google Earth (.kml, .kmz)
+ [x] GPS eXchange Format (.gpx)
+ [ ] Hancom Hanword (.hwp)
+ [x] Image files (.jpeg, .png, .gif, .webp)
+ [x] Microsoft Excel 2007+(.xlsx)
+ [ ] Microsoft Excel 2003 (.xls)
+ [x] Microsoft PowerPoint 2007+(.pptx)
+ [ ] Microsoft PowerPoint 2003 (.ppt)
+ [x] Microsoft Word 2007+(.docx)
+ [ ] Microsoft Word 2003 (.doc)
+ [x] MP3 (.mp3)
+ [x] MP4 (.mp4)
+ [x] OpenOffice presentation (.odp)
+ [x] OpenOffice spreadsheet (.ods)
+ [x] OpenOffice text (.odt)
+ [ ] Rich Text Format (.rtf)
+ [ ] Scalable Vector Graphics (.svg)
+ [ ] TeX/LaTeX (.tex)

### **Pull requests are welcome!**

**Comment by kevinborras** [comment]
I am working on the following libraries:

+ [ ] KML
+ [ ] DOC
+ [ ] XLS
+ [ ] PPT

KML one is almost done and I have the others started also.
I'm planning on work on RTF also if nobody takes it.

**Comment by DamiaPoquet** [comment]
We still need to work on this plugins for future releases.

**Comment by DamiaPoquet** [comment]
Let's open an issue for each plugin and assign it to a milestone.
